version: '3.9'

services:
  redis:
    container_name: stockfilter-redis-db
    image: redis:latest
    restart: unless-stopped
    environment:
        REDIS_DISABLE_DEFAULT_USER: true
        REDIS_USERNAME: root
        REDIS_PASSWORD: wgUn4Mlryn3tGiRns45ak83iaGXcH0xy
    volumes:
      - redis:/data

  mongodb:
    container_name: stockfilter-mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: stockfilter-app
        MONGO_INITDB_ROOT_PASSWORD: wgUn4Mlryn3tGiRns45ak83iaGXcH0xy
    volumes:
      - mongodb:/data

  app:
    container_name: stockfilter-app
    build: .
    restart: unless-stopped
    ports: 
      - 3003:3000
    volumes:
      - public:/app/public
    environment:
      FINVIZ_BASE_URL: 'https://finviz.com/screener.ashx?v=111&f=cap_smallover&o=company'
      FINVIZ_EXCLUDE_URL: 'https://finviz.com/screener.ashx?v=111&f=cap_small,sec_financial&o=company'
      YAHOO_FINANCE_URL: 'https://finance.yahoo.com/quote'
      REDIS_URL: 'redis://127.0.0.1:6379'
      NODE_ENV: 'production'
      FETCH_ON_START: 1
      MONGODB_URL: 'mongodb://stockfilter-app:wgUn4Mlryn3tGiRns45ak83iaGXcH0xy@127.0.0.1:27017/yahoo-scraper?authSource=admin'
    depends_on:
      - redis
      - mongodb

volumes:
  redis: {}
  public: {}
  mongodb: {}
